### ISSUE TITLE
Tag inheritance can be broken with empty tag values

### ISSUE THREAD

**Issue by daxxx** [serverless-operations/serverless-step-functions#301]
# This is a (Bug Report / Feature Proposal)

## Description
For bug reports:
* What went wrong?
When tags are empty an exception is raised.

* What did you expect should have happened?
Empty tags should be set empty.

* What stacktrace or error message from your provider did you see?
  TypeError: Cannot read property 'toString' of undefined
      at -\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileStateMachines.js:27:64
      at -\node_modules\lodash\lodash.js:4905:15
      at baseForOwn (-\node_modules\lodash\lodash.js:2990:24)
      at -\node_modules\lodash\lodash.js:4874:18
      at Function.forEach (-\node_modules\lodash\lodash.js:9342:14)
      at toTags (-\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileStateMachines.js:27:5)
      at -\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileStateMachines.js:106:18
      at Array.forEach (<anonymous>)
      at ServerlessStepFunctions.compileStateMachines (-\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileStateMachines.js:94:34)
...

## Additional Data
* ***Serverless Framework Core Version you're using***:
1.61.2
* ***The Plugin Version you're using***:
2.17.0
* ***Operating System***:
Windows

**Comment by horike37** [comment]
Can you share us your whole serverless.yml so that we can take a look at it?
