### ISSUE TITLE
compileIamRole - Cannot read property 'match' of null

### ISSUE THREAD

**Issue by RobBowman** [serverless-operations/serverless-step-functions#490]
# This is a (Question from a Serverless Novice)

## Description
I have the following serverless yaml that I'm using to try to deploy my first step function:

    org: bizrob
    app: flexipod-2-queue
    service: flexipod-2-queue
    
    frameworkVersion: "2 || 3"
    
    package:
      exclude:
          # list of biggest modules that are in devdepenedecies and similar
          - node_modules/aws-sdk/**
          - node_modules/serverless-domain-manager/**
          - node_modules/@serverless
          - node_modules/serverless
          - node_modules/java-invoke-local
          - node_modules/tabtab
          - node_modules/snappy
    
    custom:
      region: eu-west-1
    
    provider:
      name: aws
      runtime: nodejs14.x
    
    plugins:
      - serverless-step-functions
    functions:
      GetConfigDbConnection:
        handler: flexipod-2-queue/dbConfig.getConfigDbConnection
        environment:
          REGION: ${self:custom.region}
      GetConfigRec:
        handler: flexipod-2-queue/dbConfig.getConfigRec
        environment:
          REGION: ${self:custom.region}
      GetSelectQueries:
        handler: flexipod-2-queue/dbConfig.getSelectQueries
        environment:
          REGION: ${self:custom.region}
      PullSqlSvr:
        handler: flexipod-2-queue/pullSqlSvrData.pullSqlSvr
        environment:
          REGION: ${self:custom.region}
          API_VERSION_S3: "2006-03-01"
          API_VERSION_SQS: "2012-11-05"
          SQS_QUEUE_URL: !Ref "MyQueue"
      SendToDataLake:
        handler: queue-2-datalake/sendToDataLake.sendBatchToQueue
        environment:
          REGION: ${self:custom.region}
          API_VERSION_S3: "2006-03-01"
          API_VERSION_SQS: "2012-11-05"
          
    
    stepFunctions:
      stateMachines:
        flexipodFlow:
          name: flexipodFlow
          definition:
            StartAt: GetConfigDbConnection
            States:
              GetConfigDbConnection:
                Type: Task
                Resource:
                  Fn::GetAtt: [GetConfigDbConnection, Arn]
                Next: GetConfigRec
              GetConfigRec:
                Type: Task
                Resource:
                  Fn::GetAtt: [GetConfigRec, Arn]
                Next: GetSelectQueries
              GetSelectQueries:
                Type: Task
                Resource:
                  Fn::GetAtt: [GetSelectQueries, Arn]
                  ResultPath: $.queries
                Next: Map
              Map:
                Type: Map
                ItemsPath: $.queries
                MaxConcurrency: 2
                Next: Final State
                Iterator:
                  StartAt: PullSql
                  States:
                    PullSql:
                      Type: Task
                      Resource:
                      Fn::GetAtt: [PullSqlSvr, Arn]
              Final State:
                Type: Pass
                End: true
    resources:
      Resources:
        MyQueue:
          Type: "AWS::SQS::Queue"
          Properties:
            QueueName: "flexipod"

After running serverless deploy, I see get the following error in the vscode terminal:

    Error:
    TypeError: Cannot read property 'match' of null
        at C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileIamRole.js:472:61
        at arrayMap (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\lodash\lodash.js:653:23)
        at map (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\lodash\lodash.js:9622:14)
        at Function.flatMap (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\lodash\lodash.js:9325:26)    at ServerlessStepFunctions.getIamPermissions (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileIamRole.js:413:12)
        at C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileIamRole.js:522:56
        at Array.forEach (<anonymous>)
        at ServerlessStepFunctions.compileIamRole (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\serverless-step-functions\lib\deploy\stepFunctions\compileIamRole.js:511:32)
        at ServerlessStepFunctions.tryCatcher (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromiseCtx (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\promise.js:641:10)
        at _drainQueueStep (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\async.js:97:12)
        at _drainQueue (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (C:\GitBizTalkers\OLD_Wck_Flexipod\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (node:internal/timers:464:21)

Anyone see what I've done wrong?

## Additional Data
when I ran "serverless -v" it gave the following output 
Running "serverless" from node_modules
Framework Core: 3.2.0 (local) 3.0.0v (global)
Plugin: 6.0.0
SDK: 4.3.1

I don't know how I can tell the version of the plugin that's being used but I set this up as a new project last week.

I'm running Windows 10

**Comment by RobBowman** [comment]
Problem was due to yaml formatting. Line 192

Fn::GetAtt: [PullSqlSvr, Arn]

This needed an extra tab to indent below "Resource:"
