### ISSUE TITLE
Resource: arn:aws:states:::lambda:invoke.waitForTaskToken - Error: TypeError: state.Resource.match is not a function

### ISSUE THREAD

**Issue by ameerulislam** [serverless-operations/serverless-step-functions#512]
# This is a (Bug Report / Feature Proposal)

## Description
my step function

```
stepFunctions:
  stateMachines:
    cDisc-tid-1-stepFn:
      name: cDisctid1
      definition:
      #level 1
        StartAt: Full/Single Discovery
        States:
          Full/Single Discovery:
            Type: Choice
            Choices:
            - Variable: "$.dtype"
              StringEquals: single
              Next: Single Discovery
            - Variable: "$.dtype"
              StringEquals: full
              Next: Full Discovery
          #level 2
          Single Discovery:
            Type: Task 
            Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
            Parameters:
              FunctionName: 
                Fn::GetAtt: [singleDiscoveryOrchestrator, Arn]
              Payload: {"MyTaskToken.$": "$$.Task.Token"}
            ResultPath: "$.lambdaOutput"
            Next: Single Pass
          Full Discovery:
            Type: Task
            Resource:
              Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
            Parameters:
              FunctionName: 
                Fn::GetAtt: [somelabda, Arn]
              Payload: {"MyTaskToken.$": "$$.Task.Token"}
            ResultPath: "$.lambdaOutput"
            Next: Full Pass
          #level 3
          Single Pass:
            Type: Pass
            End: true
          Full Pass:
            Type: Pass
            End: true
            
```

For bug reports:
* What went wrong?
Resource: arn:aws:states:::lambda:invoke.waitForTaskToken is generating 
`Error: TypeError: state.Resource.match is not a function`

* What did you expect should have happened?
It should have deployed the resource

## Additional Data
* ***Serverless Framework Core Version you're using***:
* Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2

* ***The Plugin Version you're using***:
*  "dependencies": {
    "serverless": "^3.19.0",
    "serverless-python-requirements": "^5.2.2"
  },
  "devDependencies": {
    "serverless-iam-roles-per-function": "^3.2.0",
    "serverless-step-functions": "^3.7.0"
  }

* ***Operating System***:
mac - darwin

* ***Stack Trace***:
Error:
TypeError: state.Resource.match is not a function
    at /[Removed]/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:474:61
    at arrayMap (/[Removed]/node_modules/lodash/lodash.js:653:23)
    at map (/[Removed]/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/[Removed]/node_modules/lodash/lodash.js:9325:26)
    at ServerlessStepFunctions.getIamPermissions (/[Removed]/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:413:12)
    at /[Removed]/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:524:56
    at Array.forEach (<anonymous>)
    at ServerlessStepFunctions.compileIamRole (/[Removed]/node_modules/serverless-step-functions/lib/deploy/stepFunctions/compileIamRole.js:513:32)
    at ServerlessStepFunctions.tryCatcher (/[Removed]/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/[Removed]/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/[Removed]/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/[Removed]/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/[Removed]/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/[Removed]/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/[Removed]/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/[Removed]/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
* ***Provider Error messages***:
Error:
TypeError: state.Resource.match is not a function

**Comment by KillDozerX2** [comment]
@ameerulislam maybe change 
```yml
Resource:
  Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
```
to 
```yml
Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
```

You're using it correctly in the first Task. This isn't a bug.

**Comment by ameerulislam** [comment]
> @ameerulislam maybe change
> 
> ```yaml
> Resource:
>   Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
> ```
> 
> to
> 
> ```yaml
> Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
> ```
> 
> You're using it correctly in the first Task. This isn't a bug.

Hei Interesting catch. Thanks! I totally didn't see that duplication. Might work after this. However I have already used CDK to deploy my app and left serverless.com framework.

**Comment by KillDozerX2** [comment]
That's sad to hear, perhaps we should close this issue then?

**Comment by ameerulislam** [comment]
Yes sure. Since the answer came after long time I had to finish my task.
Thanks again
